
services:
  db:
    image: postgres:16-alpine
    container_name: tp6_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tp6_progavanz
    ports:
      - "5432:5432"
    volumes:
      - tp6_pgdata:/var/lib/postgresql/data
volumes:
  tp6_pgdata:
